In [137]:
import sys
import os
yelp_category = "learn"
if "/opt/condaenv/anaconda2/envs/sentimentInduction" not in sys.path:
    sys.path.append("/opt/condaenv/anaconda2/envs/sentimentInduction")
if "/opt/condaenv/anaconda2/envs/sentimentInduction/lib/python2.7/site-packages" not in sys.path:
    sys.path.append("/opt/condaenv/anaconda2/envs/sentimentInduction/lib/python2.7/site-packages")
import pandas as pd
from socialsentRun.socialconfig import config
COLLECT_ACCURACIS_DIR = config.get("COLLECT_ACCURACIS_DIR")
import ujson
open_file = os.path.join(COLLECT_ACCURACIS_DIR,"{cat}_evaluations_all.txt".format(cat=yelp_category))
dfv = pd.read_json(open_file,orient='records',lines=True,encoding="utf-8")
dfv.head()

   accuracy emb_params     method vocab_sz
0     61.41    w4_d100  rand_walk   tp5000
1     62.36    w2_d300  rand_walk   tp5000
2     64.88    w3_d200  rand_walk   tp5000
3     66.48    w4_d200  rand_walk   tp5000
4     64.05    w3_d100  rand_walk   tp5000

In [138]:
dfmeans_vocab_sz = dfv.copy().set_index(['vocab_sz','method'])
dfmeans_vocab_sz["mean_acccuracy_all_vocab_sz"] = dfmeans_vocab_sz.groupby(['vocab_sz','method'])['accuracy'].mean()
# dfmeans_vocab_sz["var_acccuracy_all_vocab_sz"] = dfmeans_vocab_sz.groupby(['vocab_sz','method'])['accuracy'].var()
dfmeans_vocab_sz.drop(['accuracy','emb_params'],inplace=True,axis=1)
dfmeans_vocab_sz = dfmeans_vocab_sz.reset_index()
dfmeans_vocab_sz = dfmeans_vocab_sz.drop_duplicates()
dfmeans_vocab_sz.head(1)

  vocab_sz     method  mean_acccuracy_all_vocab_sz
0   tp5000  rand_walk                    64.945556

In [139]:
dfmeans_vocab_sz = dfmeans_vocab_sz.set_index(['vocab_sz','method'])
dfmeans_vocab_sz = dfmeans_vocab_sz.round(2)
dfmeans_vocab_sz = dfmeans_vocab_sz.unstack(1)
dfmeans_params.to_csv(open_file.replace("evaluations","evaluations_{cat}_mean_of_vocab_sz".format(cat=yelp_category)))
dfmeans_vocab_sz.head()

         mean_acccuracy_all_vocab_sz                                          \
method                       densify grap_prop labe_prop_cont labe_prop_prob
vocab_sz
tp10000                        69.41     42.99          69.56          69.27
tp15000                        68.84     49.07          69.92          70.26
tp20000                        68.67     47.27          70.45          71.06
tp5000                         70.66     41.29          69.74          69.86


method   rand_walk
vocab_sz
tp10000      62.03
tp15000      61.82
tp20000      61.99
tp5000       64.95

In [140]:
dfmeans_params = dfv.copy().set_index(['emb_params','method'])
dfmeans_params["mean_acccuracy_all_params"] = dfmeans_params.groupby(['emb_params','method'])['accuracy'].mean()
# dfmeans_params["var_acccuracy_all_vocab_sz"] = dfmeans_params.groupby(['vocab_sz','method'])['accuracy'].var()
dfmeans_params.drop(['accuracy','vocab_sz'],inplace=True,axis=1)
dfmeans_params = dfmeans_params.reset_index()
dfmeans_params = dfmeans_params.drop_duplicates()
dfmeans_params.head(1)

  emb_params     method  mean_acccuracy_all_params
0    w4_d100  rand_walk                    63.7725

In [141]:
dfmeans_params = dfmeans_params.set_index(['emb_params','method'])
dfmeans_params = dfmeans_params.round(2)
dfmeans_params = dfmeans_params.unstack(1)
dfmeans_params.head(9)

           mean_acccuracy_all_params                                          \
method                       densify grap_prop labe_prop_cont labe_prop_prob
emb_params
w2_d100                        72.84     40.97          69.15          70.13
w2_d200                        73.74     39.47          68.57          68.08
w2_d300                        68.11     38.82          68.66          68.94
w3_d100                        71.71     54.53          70.15          70.46
w3_d200                        71.41     48.10          70.55          70.79
w3_d300                        69.90     42.27          69.60          68.77
w4_d100                        66.19     48.97          70.62          71.44
w4_d200                        64.64     43.01          71.06          71.26
w4_d300                        66.01     50.27          70.90          71.16


method     rand_walk
emb_params
w2_d100        62.33
w2_d200        60.95
w2_d300        60.97
w3_d100        62.26
w3_d200        63.50
w3_d300        61.78
w4_d100        63.77
w4_d200        64.24
w4_d300        64.46

In [131]:
dfmeans_params.to_html("evaluations_{cat}_mean_of_params.html".format(cat=yelp_category))

In [146]:
dfmeans_params.stack().query('method == "labe_prop_cont"')['mean_acccuracy_all_params'].values

array([69.15, 68.57, 68.66, 70.15, 70.55, 69.6 , 70.62, 71.06, 70.9 ])