In [31]:
import sys
import os
if "/opt/condaenv/anaconda2/envs/sentimentInduction" not in sys.path:
    sys.path.append("/opt/condaenv/anaconda2/envs/sentimentInduction")
if "/opt/condaenv/anaconda2/envs/sentimentInduction/lib/python2.7/site-packages" not in sys.path:
    sys.path.append("/opt/condaenv/anaconda2/envs/sentimentInduction/lib/python2.7/site-packages")
import pandas as pd
from socialsentRun.socialconfig import config
COLLECT_ACCURACIS_DIR = config.get("COLLECT_ACCURACIS_DIR")
import ujson
open_file = os.path.join(COLLECT_ACCURACIS_DIR,"services_evaluations_all.txt")
dfv = pd.read_json(open_file,orient='records',lines=True,encoding="utf-8")
dfv.head()

   accuracy emb_params     method vocab_sz
0     77.88    w4_d100  rand_walk   tp5000
1     79.36    w2_d300  rand_walk   tp5000
2     78.07    w3_d200  rand_walk   tp5000
3     78.78    w4_d200  rand_walk   tp5000
4     78.23    w3_d100  rand_walk   tp5000

In [32]:
dfmeans_vocab_sz = dfv.copy().set_index(['vocab_sz','method'])
dfmeans_vocab_sz["mean_acccuracy_all_vocab_sz"] = dfmeans_vocab_sz.groupby(['vocab_sz','method'])['accuracy'].mean()
# dfmeans_vocab_sz["var_acccuracy_all_vocab_sz"] = dfmeans_vocab_sz.groupby(['vocab_sz','method'])['accuracy'].var()
dfmeans_vocab_sz.drop(['accuracy','emb_params'],inplace=True,axis=1)
dfmeans_vocab_sz = dfmeans_vocab_sz.reset_index()
dfmeans_vocab_sz = dfmeans_vocab_sz.drop_duplicates()
dfmeans_vocab_sz.head(1)

  vocab_sz     method  mean_acccuracy_all_vocab_sz
0   tp5000  rand_walk                    78.482222

In [33]:
dfmeans_vocab_sz = dfmeans_vocab_sz.set_index(['vocab_sz','method'])
dfmeans_vocab_sz = dfmeans_vocab_sz.round(2)
dfmeans_vocab_sz = dfmeans_vocab_sz.unstack(1)
dfmeans_vocab_sz.head()

         mean_acccuracy_all_vocab_sz                                          \
method                       densify grap_prop labe_prop_cont labe_prop_prob
vocab_sz
tp10000                        29.88     72.50          78.71          78.79
tp15000                        22.98     72.96          78.77          78.25
tp20000                        35.49     71.88          78.53          77.36
tp25000                        23.32     72.84          78.83          78.75
tp5000                         38.61     75.02          78.71          78.00


method   rand_walk
vocab_sz
tp10000      75.54
tp15000      74.86
tp20000      73.97
tp25000      75.95
tp5000       78.48

In [34]:
dfmeans_params = dfv.copy().set_index(['emb_params','method'])
dfmeans_params["mean_acccuracy_all_params"] = dfmeans_params.groupby(['emb_params','method'])['accuracy'].mean()
# dfmeans_params["var_acccuracy_all_vocab_sz"] = dfmeans_params.groupby(['vocab_sz','method'])['accuracy'].var()
dfmeans_params.drop(['accuracy','vocab_sz'],inplace=True,axis=1)
dfmeans_params = dfmeans_params.reset_index()
dfmeans_params = dfmeans_params.drop_duplicates()
dfmeans_params.head(1)

  emb_params     method  mean_acccuracy_all_params
0    w4_d100  rand_walk                     74.162

In [35]:
dfmeans_params = dfmeans_params.set_index(['emb_params','method'])
dfmeans_params = dfmeans_params.round(2)
dfmeans_params = dfmeans_params.unstack(1)
dfmeans_params.head()

           mean_acccuracy_all_params                                          \
method                       densify grap_prop labe_prop_cont labe_prop_prob
emb_params
w2_d100                        18.13     70.56          78.85          77.99
w2_d200                        18.13     73.61          78.96          79.47
w2_d300                        19.03     73.63          79.59          79.93
w3_d100                        33.79     69.72          78.96          76.63
w3_d200                        48.72     74.36          79.11          78.36


method     rand_walk
emb_params
w2_d100        75.69
w2_d200        75.29
w2_d300        76.99
w3_d100        75.95
w3_d200        76.51