In [1]:
import sys
import os
if "/opt/condaenv/anaconda2/envs/sentimentInduction" not in sys.path:
    sys.path.append("/opt/condaenv/anaconda2/envs/sentimentInduction")
if "/opt/condaenv/anaconda2/envs/sentimentInduction/lib/python2.7/site-packages" not in sys.path:
    sys.path.append("/opt/condaenv/anaconda2/envs/sentimentInduction/lib/python2.7/site-packages")
import pandas as pd
from socialsentRun.socialconfig import config
COLLECT_ACCURACIS_DIR = config.get("COLLECT_ACCURACIS_DIR")
import ujson
open_file = os.path.join(COLLECT_ACCURACIS_DIR,"food_evaluations_by_params.txt")
dfv = pd.read_json(open_file,orient='records',lines=True,encoding="utf-8")
dfv.head()

    accuracy emb_params       method
0  75.265834    w4_d100  random_walk
1  74.475258    w2_d300  random_walk
2  74.844498    w3_d200  random_walk
3  75.593756    w4_d200  random_walk
4  75.618466    w3_d100  random_walk

In [113]:
dfv = dfv.set_index(['emb_params','method'])
dfv.head()

                         accuracy
emb_params method
w4_d100    random_walk  75.265834
w2_d300    random_walk  74.475258
w3_d200    random_walk  74.844498
w4_d200    random_walk  75.593756
w3_d100    random_walk  75.618466

In [114]:
dfmeanallvocabs = dfv.copy()

In [115]:
dfmeanallvocabs["mean_accuracy_diff_vocab_sizes"] = dfmeanallvocabs.groupby(['emb_params','method'])['accuracy'].mean()
dfmeanallvocabs['var_diff_vocab_sizes'] = dfmeanallvocabs.groupby(['emb_params','method'])['accuracy'].var()
dfmeanallvocabs.drop(['accuracy'],inplace=True,axis=1)
dfmeanallvocabs.head()

                        mean_accuracy_diff_vocab_sizes  var_diff_vocab_sizes
emb_params method
w4_d100    random_walk                       75.015930              0.065489
w2_d300    random_walk                       74.345763              0.094294
w3_d200    random_walk                       75.727033              0.268440
w4_d200    random_walk                       75.003851              0.191327
w3_d100    random_walk                       74.772790              0.343697

In [88]:
# dfmeanallvocabs_stacked.unstack(0)

In [116]:
dfmeanallvocabs = dfmeanallvocabs.reset_index()
dfmeanallvocabs = dfmeanallvocabs.drop_duplicates()
len(dfmeanallvocabs)

45

In [117]:
dfmeanallvocabs.head()

,emb_params,method,mean_accuracy_diff_vocab_sizes,var_diff_vocab_sizes
0,w4_d100,random_walk,75.015930,0.065489
1,w2_d300,random_walk,74.345763,0.094294
2,w3_d200,random_walk,75.727033,0.268440
3,w4_d200,random_walk,75.003851,0.191327
4,w3_d100,random_walk,74.772790,0.343697

In [118]:
dfmeanallvocabs = dfmeanallvocabs.set_index(['emb_params','method'])
dfmeanallvocabs.drop('var_diff_vocab_sizes',axis=1,inplace=True)
dfmeanallvocabs.head()

                        mean_accuracy_diff_vocab_sizes
emb_params method
w4_d100    random_walk                       75.015930
w2_d300    random_walk                       74.345763
w3_d200    random_walk                       75.727033
w4_d200    random_walk                       75.003851
w3_d100    random_walk                       74.772790

In [119]:
dfmeanallvocabs.unstack('method') # Note for paper

           mean_accuracy_diff_vocab_sizes                  \
method                            densify graph_propagate
emb_params
w2_d100                         80.445987       69.050479
w2_d200                         80.654403       69.179683
w2_d300                         80.571242       69.851895
w3_d100                         81.085231       71.849804
w3_d200                         81.061350       70.272868
w3_d300                         80.860776       71.558924
w4_d100                         80.816642       66.765701
w4_d200                         81.182752       72.292029
w4_d300                         80.830609       71.766277

                                                                     \
method     label_propagate_continuous label_propagate_probabilistic
emb_params
w2_d100                     73.735175                     73.511687
w2_d200                     73.754178                     71.740033
w2_d300                     73.913174                     73.474963
w3_d100                     73.895934                     73.625490
w3_d200                     74.434857                     73.759341
w3_d300                     73.979018                     73.077739
w4_d100                     74.159603                     73.191779
w4_d200                     74.138257                     73.397510
w4_d300                     74.135952                     73.452142


method     random_walk
emb_params
w2_d100      74.382909
w2_d200      74.319646
w2_d300      74.345763
w3_d100      74.772790
w3_d200      75.727033
w3_d300      75.067304
w4_d100      75.015930
w4_d200      75.003851
w4_d300      74.895905

In [111]:
dfmeanallvocabs.to_html("mean_accuracies_for_all_methods_types_and_training_param_type.html")

In [120]:
dfmeanallmethodsperparam = dfmeanallvocabs.copy()
dfmeanallmethodsperparam = dfmeanallmethodsperparam.set_index(['emb_params'])
dfmeanallmethodsperparam.head()

KeyError: 'emb_params'

In [74]:
dfmeanallmethodsperparam["mean_accuracy_all_ind_methods"] = dfmeanallmethodsperparam.groupby(['emb_params'])['mean_accuracy_diff_vocab_sizes'].mean()
dfmeanallmethodsperparam['var_all_ind_methods'] = dfmeanallmethodsperparam.groupby(['emb_params'])['mean_accuracy_diff_vocab_sizes'].var()
dfmeanallmethodsperparam.drop(['mean_accuracy_diff_vocab_sizes','var_diff_vocab_sizes'],axis=1,inplace=True)
dfmeanallmethodsperparam.head()

                 method  mean_accuracy_all_ind_methods  var_all_ind_methods
emb_params
w4_d100     random_walk                       0.739899             0.002513
w2_d300     random_walk                       0.744314             0.001497
w3_d200     random_walk                       0.750511             0.001536
w4_d200     random_walk                       0.752029             0.001217
w3_d100     random_walk                       0.750458             0.001253

In [75]:
dfmeanallmethodsperparam = dfmeanallmethodsperparam.reset_index()
dfmeanallmethodsperparam.head()

  emb_params       method  mean_accuracy_all_ind_methods  var_all_ind_methods
0    w4_d100  random_walk                       0.739899             0.002513
1    w2_d300  random_walk                       0.744314             0.001497
2    w3_d200  random_walk                       0.750511             0.001536
3    w4_d200  random_walk                       0.752029             0.001217
4    w3_d100  random_walk                       0.750458             0.001253

In [76]:
dfmeanallmethodsperparam = dfmeanallmethodsperparam.drop_duplicates()
dfmeanallmethodsperparam # Note for paper

,emb_params,method,mean_accuracy_all_ind_methods,var_all_ind_methods
0,w4_d100,random_walk,0.739899,0.002513
1,w2_d300,random_walk,0.744314,0.001497
2,w3_d200,random_walk,0.750511,0.001536
3,w4_d200,random_walk,0.752029,0.001217
4,w3_d100,random_walk,0.750458,0.001253
5,w4_d300,random_walk,0.750162,0.001190
6,w2_d100,random_walk,0.742252,0.001656
7,w2_d200,random_walk,0.739296,0.001819
8,w3_d300,random_walk,0.749088,0.001272
9,w4_d100,label_propagate_probabilistic,0.739899,0.002513
10,w2_d300,label_propagate_probabilistic,0.744314,0.001497
11,w3_d200,label_propagate_probabilistic,0.750511,0.001536
12,w4_d200,label_propagate_probabilistic,0.752029,0.001217
13,w3_d100,label_propagate_probabilistic,0.750458,0.001253
14,w4_d300,label_propagate_probabilistic,0.750162,0.001190
15,w2_d100,label_propagate_probabilistic,0.742252,0.001656
16,w2_d200,label_propagate_probabilistic,0.739296,0.001819
17,w3_d300,label_propagate_probabilistic,0.749088,0.001272
18,w4_d100,densify,0.739899,0.002513
19,w2_d300,densify,0.744314,0.001497
20,w3_d200,densify,0.750511,0.001536
21,w4_d200,densify,0.752029,0.001217
22,w3_d100,densify,0.750458,0.001253
23,w4_d300,densify,0.750162,0.001190
24,w2_d100,densify,0.742252,0.001656
25,w2_d200,densify,0.739296,0.001819
26,w3_d300,densify,0.749088,0.001272
27,w4_d100,label_propagate_continuous,0.739899,0.002513
28,w2_d300,label_propagate_continuous,0.744314,0.001497
29,w3_d200,label_propagate_continuous,0.750511,0.001536
30,w4_d200,label_propagate_continuous,0.752029,0.001217
31,w3_d100,label_propagate_continuous,0.750458,0.001253
32,w4_d300,label_propagate_continuous,0.750162,0.001190
33,w2_d100,label_propagate_continuous,0.742252,0.001656
34,w2_d200,label_propagate_continuous,0.739296,0.001819
35,w3_d300,label_propagate_continuous,0.749088,0.001272
36,w4_d100,graph_propagate,0.739899,0.002513
37,w2_d300,graph_propagate,0.744314,0.001497
38,w3_d200,graph_propagate,0.750511,0.001536
39,w4_d200,graph_propagate,0.752029,0.001217
40,w3_d100,graph_propagate,0.750458,0.001253
41,w4_d300,graph_propagate,0.750162,0.001190
42,w2_d100,graph_propagate,0.742252,0.001656
43,w2_d200,graph_propagate,0.739296,0.001819
44,w3_d300,graph_propagate,0.749088,0.001272

In [69]:
dfmeanallmethodsperparam['mean_of_mean'] = dfmeanallmethodsperparam['mean_accuracy_all_ind_methods'].mean()

In [71]:
dfmeanallmethodsperparam['var_of_mean'] = dfmeanallmethodsperparam['mean_accuracy_all_ind_methods'].var()
dfmeanallmethodsperparam

,emb_params,mean_accuracy_all_ind_methods,var_all_ind_methods,mean_of_mean,var_of_mean
0,w4_d100,0.739899,0.002513,0.746445,0.000025
1,w2_d300,0.744314,0.001497,0.746445,0.000025
2,w3_d200,0.750511,0.001536,0.746445,0.000025
3,w4_d200,0.752029,0.001217,0.746445,0.000025
4,w3_d100,0.750458,0.001253,0.746445,0.000025
5,w4_d300,0.750162,0.001190,0.746445,0.000025
6,w2_d100,0.742252,0.001656,0.746445,0.000025
7,w2_d200,0.739296,0.001819,0.746445,0.000025
8,w3_d300,0.749088,0.001272,0.746445,0.000025

In [72]:
dfmeanallmethodsperparam['std_of_mean'] = dfmeanallmethodsperparam['mean_accuracy_all_ind_methods'].std()
dfmeanallmethodsperparam

,emb_params,mean_accuracy_all_ind_methods,var_all_ind_methods,mean_of_mean,var_of_mean,std_of_mean
0,w4_d100,0.739899,0.002513,0.746445,0.000025,0.005009
1,w2_d300,0.744314,0.001497,0.746445,0.000025,0.005009
2,w3_d200,0.750511,0.001536,0.746445,0.000025,0.005009
3,w4_d200,0.752029,0.001217,0.746445,0.000025,0.005009
4,w3_d100,0.750458,0.001253,0.746445,0.000025,0.005009
5,w4_d300,0.750162,0.001190,0.746445,0.000025,0.005009
6,w2_d100,0.742252,0.001656,0.746445,0.000025,0.005009
7,w2_d200,0.739296,0.001819,0.746445,0.000025,0.005009
8,w3_d300,0.749088,0.001272,0.746445,0.000025,0.005009