In [20]:
import sys
import os
import pandas as pd
from socialconfig import config
COLLECT_ACCURACIS_DIR = "/opt/condaenv/anaconda2/envs/sentimentInduction/socialsentRun/MeanPolaritiesByCategory/shopping/vocab_top20000"
import ujson
open_file = os.path.join(COLLECT_ACCURACIS_DIR,"shopping_vocab_top20000_mean_polarities.txt")
dfv = pd.read_json(open_file,orient='records',lines=True,encoding="utf-8")
dfv.head()

,densify,graph_propagate,label_propagate_continuous,label_propagate_probabilistic,method_count,random_walk,token
0,0.47,-0.34,-0.65,-0.68,5,-0.91,paperless
1,NaN,NaN,NaN,NaN,0,NaN,compare-shop
2,0.08,-0.17,-0.04,-0.04,5,-0.14,refridgerated
3,NaN,NaN,NaN,NaN,0,NaN,mid-week
4,0.06,-0.17,-0.02,-0.02,5,-0.11,mustachio

In [21]:
from socialconfig import FOOD_POSITIVE_SEEDS,FOOD_NEGATIVE_SEEDS,BARS_POSITIVE_SEEDS,BARS_NEGATIVE_SEEDS,LEISURE_POSITIVE_SEEDS,LEISURE_NEGATIVE_SEEDS,GROOMING_POSITIVE_SEEDS,GROOMING_NEGATIVE_SEEDS,HEALTH_POSITIVE_SEEDS,HEALTH_NEGATIVE_SEEDS,LEARN_POSITIVE_SEEDS,LEARN_NEGATIVE_SEEDS,SHOPPING_POSITIVE_SEEDS,SHOPPING_NEGATIVE_SEEDS,PLANNING_POSITIVE_SEEDS,PLANNING_NEGATIVE_SEEDS,SERVICES_POSITIVE_SEEDS,SERVICES_NEGATIVE_SEEDS,SPORTS_POSITIVE_SEEDS,SPORTS_NEGATIVE_SEEDS,MUNICIPAL_POSITIVE_SEEDS,MUNICIPAL_NEGATIVE_SEEDS

In [22]:
SHOPPING_POSITIVE_SEEDS.extend(SHOPPING_NEGATIVE_SEEDS)

In [23]:
dfgt4 = dfv[dfv['method_count'] > 4]

In [24]:
dfgt4 = dfgt4[~dfgt4['token'].isin(SHOPPING_POSITIVE_SEEDS)]

In [25]:
dfgt4.shape

(10497, 7)

In [26]:

dfgt4 = dfgt4.set_index('token')
dfgt4.drop(['method_count'],inplace=True,axis=1)
"Ok"

'Ok'

In [27]:
dfgt4['mean_pol'] = dfgt4.mean(axis=1)
dfgt4['var'] = dfgt4.var(axis=1)

In [28]:
dfgt4 = dfgt4.sort_values('mean_pol',ascending=False)
dfgt4.head()

,densify,graph_propagate,label_propagate_continuous,label_propagate_probabilistic,random_walk,mean_pol,var
token,,,,,,,
excellent,-0.44,0.89,0.84,0.84,0.99,0.624,0.286024
attentive,-0.46,0.89,0.83,0.84,0.99,0.618,0.293736
affordable,-0.37,0.74,0.67,0.68,0.97,0.538,0.217896
try-you,-0.43,0.20,0.74,0.78,0.98,0.454,0.262144
patient,-0.41,0.36,0.59,0.60,0.92,0.412,0.200696

In [29]:
str(dfgt4['var'].mean())[:5]

'0.047'

In [30]:
dfgt4.tail()

,densify,graph_propagate,label_propagate_continuous,label_propagate_probabilistic,random_walk,mean_pol,var
token,,,,,,,
unaccomodating,0.61,-0.47,-0.87,-0.88,-0.97,-0.516,0.346784
fine,0.43,-0.75,-0.71,-0.70,-0.95,-0.536,0.241504
corporate,0.47,-0.77,-0.79,-0.78,-0.96,-0.566,0.273224
terrible,0.62,-0.90,-0.94,-0.94,-0.99,-0.630,0.391440
poor,0.53,-0.99,-0.91,-0.91,-0.98,-0.652,0.350416

In [73]:
w.columns

Index([                        u'token',                       u'densify',
                     u'graph_propagate',    u'label_propagate_continuous',
       u'label_propagate_probabilistic',                   u'random_walk',
                            u'mean_pol',                           u'var'],
      dtype='object')

In [81]:
w = dfgt4.copy()
w = w.reset_index()

w.drop([   u'densify',
                     u'graph_propagate',    u'label_propagate_continuous',
       u'label_propagate_probabilistic',                   u'random_walk','var'],inplace=True,axis=1)
w=w.rename({"mean_pol":"shop"},axis=1)
w.to_csv("common_shopping_words.csv")

In [40]:
dfgt5 = dfgt4.sort_values('var',ascending=False)
dfgt5.head()

,densify,graph_propagate,label_propagate_continuous,label_propagate_probabilistic,random_walk,mean_pol,var
token,,,,,,,
one-hundred-seventy-five,0.96,-0.17,-0.83,-0.93,-0.99,-0.392,0.543216
thy,0.82,-0.25,-0.86,-0.93,-0.99,-0.442,0.468536
slalom,0.83,-0.18,-0.82,-0.88,-0.98,-0.406,0.460864
ink-printed,0.78,-0.19,-0.78,-0.87,-0.98,-0.408,0.427576
staunch,0.74,-0.27,-0.86,-0.94,-0.98,-0.462,0.427376

In [55]:
i=18
dfgt5[i*5:i*5+5]

,densify,graph_propagate,label_propagate_continuous,label_propagate_probabilistic,random_walk,mean_pol,var
token,,,,,,,
spilling,0.60,-0.31,-0.74,-0.80,-0.90,-0.430,0.305840
near-by,0.58,-0.37,-0.77,-0.82,-0.92,-0.460,0.305400
eloquent,0.59,-0.25,-0.71,-0.78,-0.93,-0.416,0.304544
100-month,0.60,-0.25,-0.70,-0.76,-0.93,-0.408,0.304536
fustrated,0.60,-0.25,-0.72,-0.77,-0.91,-0.410,0.304280

In [52]:
dfgt5 = dfgt4.sort_values('var',ascending=False)
dfgt5.tail()

,densify,graph_propagate,label_propagate_continuous,label_propagate_probabilistic,random_walk,mean_pol,var
token,,,,,,,
skate-related,0.01,-0.13,-0.07,-0.08,-0.03,-0.060,0.002240
arduous,-0.01,-0.14,-0.03,-0.02,-0.06,-0.052,0.002216
mec,-0.05,-0.17,-0.07,-0.07,-0.04,-0.080,0.002160
pike,-0.04,-0.17,-0.06,-0.06,-0.09,-0.084,0.002104
10-2,-0.03,-0.15,-0.05,-0.04,-0.08,-0.070,0.001880

In [18]:
dfgt5[dfgt5['var'] >= 0.30].shape

(100, 7)

In [62]:
dfgt5.columns

Index([                      u'densify',               u'graph_propagate',
          u'label_propagate_continuous', u'label_propagate_probabilistic',
                         u'random_walk',                      u'mean_pol',
                                 u'var'],
      dtype='object')

In [68]:
d = pd.DataFrame(dfgt5[:5])

In [69]:
d

,densify,graph_propagate,label_propagate_continuous,label_propagate_probabilistic,random_walk,mean_pol,var
token,,,,,,,
one-hundred-seventy-five,0.96,-0.17,-0.83,-0.93,-0.99,-0.392,0.543216
thy,0.82,-0.25,-0.86,-0.93,-0.99,-0.442,0.468536
slalom,0.83,-0.18,-0.82,-0.88,-0.98,-0.406,0.460864
ink-printed,0.78,-0.19,-0.78,-0.87,-0.98,-0.408,0.427576
staunch,0.74,-0.27,-0.86,-0.94,-0.98,-0.462,0.427376